Create portfolio projects
nicupop729/Web_Developer_Portfolio pull request #2
Opened 2021-09-16 22:32 UTC by nicupop729

## Portfolio Project

For this branch, I have worked on the following:
- create HTML for the Work Experience section and the Knowledge - Skills section;
- add CSS for the same sections;

2021-09-16 23:24 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @nicupop729  You did a great job so far 👏🏼 👏🏼 

- Commit messages are professional
- The pull request is descriptive
- You did a good job in following the design
- Well done on using HTML semantic tags

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-16 23:24 UTC, safafa commented on index.html
> +            <img
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") list belong to the about me section. Kindly move it there.

2021-09-16 23:24 UTC, safafa commented on src/style.css
> +
![image](https://user-images.githubusercontent.com/43698511/133697472-63ba5316-e60f-43bf-8b42-0b253ee65c84.png)

- [ ] As you can see in the picture the horizontal scroll bar is showing for mobile view under 432px. Kindly fix the issue.
![image](https://user-images.githubusercontent.com/43698511/133697602-e700fe1b-5eb5-4329-88e0-549bf5364c1f.png)
original design:
![image](https://user-images.githubusercontent.com/43698511/133697631-554cd974-8795-4eaa-82c0-36fb1f73a485.png)

- [ ] As you can see in the picture your project looks a bit different from the original design in mobile view. Kindly fix the issue.

2021-09-17 02:00 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @nicupop729 , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 02:11 UTC, merged